/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CVEntry {
  'id' : string,
  'title' : string,
  'yearRange' : string,
  'type' : CVType,
  'description' : string,
  'organization' : string,
}
export type CVType = { 'education' : null } |
  { 'experience' : null } |
  { 'certification' : null };
export interface ContactFormSubmission {
  'id' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface PricingPackage {
  'id' : string,
  'duration' : string,
  'name' : string,
  'description' : string,
  'highlighted' : boolean,
  'bulletPoints' : Array<string>,
  'price' : number,
}
export interface SessionContentItem {
  'id' : string,
  'title' : string,
  'description' : string,
  'iconName' : string,
}
export interface TherapistProfile {
  'bio' : string,
  'tagline' : string,
  'name' : string,
  'photo' : Uint8Array,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateCVEntry' : ActorMethod<[CVEntry], undefined>,
  'addOrUpdatePricingPackage' : ActorMethod<[PricingPackage], undefined>,
  'addOrUpdateSessionContentItem' : ActorMethod<
    [SessionContentItem],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCVEntry' : ActorMethod<[string], undefined>,
  'deletePricingPackage' : ActorMethod<[string], undefined>,
  'deleteSessionContentItem' : ActorMethod<[string], undefined>,
  'getAllCVEntries' : ActorMethod<[], Array<CVEntry>>,
  'getAllContactFormSubmissions' : ActorMethod<
    [],
    Array<ContactFormSubmission>
  >,
  'getAllPricingPackages' : ActorMethod<[], Array<PricingPackage>>,
  'getAllSessionContentItems' : ActorMethod<[], Array<SessionContentItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTherapistProfile' : ActorMethod<[], TherapistProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, [] | [string], string],
    undefined
  >,
  'updateProfilePhoto' : ActorMethod<[ExternalBlob], undefined>,
  'updateTherapistProfile' : ActorMethod<[TherapistProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];