/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CVType = IDL.Variant({
  'education' : IDL.Null,
  'experience' : IDL.Null,
  'certification' : IDL.Null,
});
export const CVEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'yearRange' : IDL.Text,
  'type' : CVType,
  'description' : IDL.Text,
  'organization' : IDL.Text,
});
export const PricingPackage = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'highlighted' : IDL.Bool,
  'bulletPoints' : IDL.Vec(IDL.Text),
  'price' : IDL.Float64,
});
export const SessionContentItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactFormSubmission = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TherapistProfile = IDL.Record({
  'bio' : IDL.Text,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'photo' : IDL.Vec(IDL.Nat8),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateCVEntry' : IDL.Func([CVEntry], [], []),
  'addOrUpdatePricingPackage' : IDL.Func([PricingPackage], [], []),
  'addOrUpdateSessionContentItem' : IDL.Func([SessionContentItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCVEntry' : IDL.Func([IDL.Text], [], []),
  'deletePricingPackage' : IDL.Func([IDL.Text], [], []),
  'deleteSessionContentItem' : IDL.Func([IDL.Text], [], []),
  'getAllCVEntries' : IDL.Func([], [IDL.Vec(CVEntry)], ['query']),
  'getAllContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllPricingPackages' : IDL.Func([], [IDL.Vec(PricingPackage)], ['query']),
  'getAllSessionContentItems' : IDL.Func(
      [],
      [IDL.Vec(SessionContentItem)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTherapistProfile' : IDL.Func([], [TherapistProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'updateProfilePhoto' : IDL.Func([ExternalBlob], [], []),
  'updateTherapistProfile' : IDL.Func([TherapistProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CVType = IDL.Variant({
    'education' : IDL.Null,
    'experience' : IDL.Null,
    'certification' : IDL.Null,
  });
  const CVEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'yearRange' : IDL.Text,
    'type' : CVType,
    'description' : IDL.Text,
    'organization' : IDL.Text,
  });
  const PricingPackage = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'highlighted' : IDL.Bool,
    'bulletPoints' : IDL.Vec(IDL.Text),
    'price' : IDL.Float64,
  });
  const SessionContentItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactFormSubmission = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TherapistProfile = IDL.Record({
    'bio' : IDL.Text,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'photo' : IDL.Vec(IDL.Nat8),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateCVEntry' : IDL.Func([CVEntry], [], []),
    'addOrUpdatePricingPackage' : IDL.Func([PricingPackage], [], []),
    'addOrUpdateSessionContentItem' : IDL.Func([SessionContentItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCVEntry' : IDL.Func([IDL.Text], [], []),
    'deletePricingPackage' : IDL.Func([IDL.Text], [], []),
    'deleteSessionContentItem' : IDL.Func([IDL.Text], [], []),
    'getAllCVEntries' : IDL.Func([], [IDL.Vec(CVEntry)], ['query']),
    'getAllContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllPricingPackages' : IDL.Func(
        [],
        [IDL.Vec(PricingPackage)],
        ['query'],
      ),
    'getAllSessionContentItems' : IDL.Func(
        [],
        [IDL.Vec(SessionContentItem)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTherapistProfile' : IDL.Func([], [TherapistProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'updateProfilePhoto' : IDL.Func([ExternalBlob], [], []),
    'updateTherapistProfile' : IDL.Func([TherapistProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };